export const fallbackImage='https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format&fit=crop&w=1200&q=80';
export const demoArticles=[
  {id:'d1',slug:'welcome-to-islamiexpress',title:'Islami Express enters a new digital era of independent daily journalism',summary:'Fast updates, trusted reporting, e-paper access and a modern reader experience in one place.',featured_image:fallbackImage,category_name:'India',category_slug:'india',author_name:'Islami Express Desk',published_at:new Date().toISOString(),like_count:124,comment_count:18,share_count:36},
  {id:'d2',slug:'morning-news-brief',title:'Morning News Brief: The major stories readers should know today',summary:'A concise look at the developments shaping the day across India and the world.',featured_image:'https://images.unsplash.com/photo-1495020689067-958852a7765e?auto=format&fit=crop&w=900&q=80',category_name:'Latest',category_slug:'latest',author_name:'News Desk',published_at:new Date().toISOString()},
  {id:'d3',slug:'digital-newsroom',title:'Inside the digital newsroom: how breaking stories move from reporter to reader',summary:'Editorial review, verification, corrections and transparent updates remain at the heart of publishing.',featured_image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=900&q=80',category_name:'Technology',category_slug:'technology',author_name:'Tech Desk',published_at:new Date().toISOString()},
  {id:'d4',slug:'sports-roundup',title:'Sports Round-up: Results, analysis and what comes next',summary:'The latest sports developments, schedules and expert analysis.',featured_image:'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=80',category_name:'Sports',category_slug:'sports',author_name:'Sports Desk',published_at:new Date().toISOString()},
  {id:'d5',slug:'business-watch',title:'Business Watch: Markets, companies and the economy in focus',summary:'Key economic developments explained for everyday readers.',featured_image:'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=900&q=80',category_name:'Business',category_slug:'business',author_name:'Business Desk',published_at:new Date().toISOString()},
  {id:'d6',slug:'culture-weekend',title:'Culture & Lifestyle: voices, ideas and stories from across communities',summary:'People, culture, food, travel and conversations that matter.',featured_image:'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80',category_name:'Lifestyle',category_slug:'lifestyle',author_name:'Features Desk',published_at:new Date().toISOString()}
];
