'use client';
import{useEffect,useState}from'react';import{clientApi}from'@/lib/api';import{ThumbsUp,Flag}from'lucide-react';
export default function Comments({articleId,enabled=true}){const[items,setItems]=useState([]);const[body,setBody]=useState('');const[msg,setMsg]=useState('');
 async function load(){try{const d=await clientApi(`/comments/article/${articleId}`);setItems(d.data||[])}catch{}}
 useEffect(()=>{load()},[articleId]);
 async function submit(e){e.preventDefault();try{const d=await clientApi(`/comments/article/${articleId}`,{method:'POST',body:JSON.stringify({body})});setBody('');setMsg(d.data.status==='pending'?'Comment submitted for moderation.':'Comment posted.');load()}catch(e){if(e.message==='Authentication required')location.href='/login?next='+encodeURIComponent(location.pathname);else setMsg(e.message)}}
 if(!enabled)return <div className="comments-closed">Comments are closed for this article.</div>;
 return <section id="comments" className="comments"><div className="section-title"><h2>Comments ({items.length})</h2></div><form className="comment-form" onSubmit={submit}><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} required placeholder="Join the conversation. Keep it respectful and relevant."/><div><small>{body.length}/2000</small><button>Post comment</button></div></form>{msg&&<p className="form-msg">{msg}</p>}<div className="comment-list">{items.map(c=><article className="comment" key={c.id}><div className="avatar">{c.name?.[0]||'U'}</div><div><div className="comment-head"><b>{c.name}</b><time>{new Date(c.created_at).toLocaleString('en-IN')}</time></div><p>{c.body}</p><div className="comment-actions"><button onClick={()=>clientApi(`/comments/${c.id}/like`,{method:'POST'}).then(load)}><ThumbsUp/> {c.like_count||0}</button><button onClick={()=>clientApi(`/comments/${c.id}/report`,{method:'POST',body:JSON.stringify({reason:'User report'})}).then(()=>setMsg('Comment reported for review.')).catch(()=>{})}><Flag/> Report</button></div></div></article>)}</div></section>
}
