'use client';
import {useState}from'react';import {ThumbsUp,MessageCircle,Bookmark,Share2,Copy,MessageCircleMore}from'lucide-react';import{clientApi}from'@/lib/api';
export default function EngagementBar({article}){const[liked,setLiked]=useState(!!article.liked_by_me);const[saved,setSaved]=useState(!!article.saved_by_me);const[count,setCount]=useState(Number(article.like_count||0));const[shareOpen,setShareOpen]=useState(false);
 const needLogin=()=>{window.location.href='/login?next='+encodeURIComponent(window.location.pathname)};
 async function toggleLike(){try{const d=await clientApi(`/interactions/${article.id}/like`,{method:'POST'});setLiked(d.liked);setCount(d.count)}catch{needLogin()}}
 async function toggleSave(){try{const d=await clientApi(`/interactions/${article.id}/save`,{method:'POST'});setSaved(d.saved)}catch{needLogin()}}
 async function share(platform){const url=window.location.href;const text=article.title;try{await clientApi(`/interactions/${article.id}/share`,{method:'POST',body:JSON.stringify({platform})})}catch{}
  const links={whatsapp:`https://wa.me/?text=${encodeURIComponent(text+' '+url)}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,x:`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,telegram:`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}`};
  if(platform==='copy'){await navigator.clipboard.writeText(url);setShareOpen(false)} else window.open(links[platform], '_blank','noopener,noreferrer');}
 return <div className="engagement"><button className={liked?'active':''} onClick={toggleLike}><ThumbsUp/> <span>{count||'Like'}</span></button><a href="#comments"><MessageCircle/><span>{article.comment_count||0} Comments</span></a><button className={saved?'active':''} onClick={toggleSave}><Bookmark/><span>{saved?'Saved':'Save'}</span></button><div className="share-wrap"><button onClick={()=>setShareOpen(v=>!v)}><Share2/><span>Share</span></button>{shareOpen&&<div className="share-menu"><button onClick={()=>share('whatsapp')}><MessageCircleMore/> WhatsApp</button><button onClick={()=>share('facebook')}>Facebook</button><button onClick={()=>share('x')}>X / Twitter</button><button onClick={()=>share('telegram')}>Telegram</button><button onClick={()=>share('copy')}><Copy/> Copy link</button></div>}</div></div>
}
